import { COLORS } from "../../../style_variables/COLORS";

export enum OverlayLayoutColors {
    SURFACE_GRADIENT_1 = COLORS.SURFACE_GRADIENT_1,
    SURFACE_GRADIENT_2 = COLORS.SURFACE_GRADIENT_2,
    SURFACE_OPACITY_2 = COLORS.NEW_SURFACE_OPACITY_2,
    SURFACE_3 = COLORS.NEW_SURFACE_3,
  }