export enum COLORS {
  NEW_SURFACE_5 = '--new-surface-surface-5',
  NEW_SURFACE_ON_SURFACE_1 = '--new-on-surface-on-surface-1',
  NEW_SURFACE_ON_SURFACE_2 = '--new-on-surface-on-surface-2',
  NEW_SURFACE_ON_SURFACE_3 = '--new-on-surface-on-surface-3',
  NEW_PRIMARY_GRADIENT = '--new-primary-primary-gradient',
  NEW_PRIMARY_GRADIENT_HOVER = '--new-primary-primary-gradient-hover',
  NEW_PRIMARY_GRADIENT_PRESSED = '--new-primary-primary-gradient-pressed',
  NEW_SURFACE_3 = '--new-surface-surface-3',
  NEW_SURFACE_OPACITY_3 = '--new-surface-surface-opacity-3',
  NEW_SURFACE_OPACITY_2 = '--new-surface-surface-opacity-2',
  NEW_OUTLINE_BORDER = '--new-outline-border-3',
  NEW_SURFACE_4 = '--new-surface-surface-4',
  SURFACE_GRADIENT_1 = '--color-surface-gradient-1',
  SURFACE_GRADIENT_2 = '--color-surface-gradient-2',
}
